version: '3.1'
services:
  db:
    image: mysql/mysql-server:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Persons
      MYSQL_USER: user_name_1
      MYSQL_PASSWORD: my-secret-pw
    ports:
      -  3306:3306

  app:
    image: njohansen/opn_server
    links:
      - db
    ports:
      - 5000:5000

  web:
    image: njohansen/opn_nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_PORT=80
    links:
      - app
